import '../models/itinerary.dart';

/// Massa de pontos de interesse mock, agrupados por cidade/bairro.
/// Usados quando não há API disponível ou como fallback offline.

// ─── LONDRES ───────────────────────────────────────────────────────────────────
const List<Place> _londonPlaces = [
  Place(
    id: 'ld-001',
    name: 'Big Ben',
    description:
        'Icônico relógio do Palácio de Westminster, símbolo de Londres.',
    category: PlaceCategory.tourist,
    latitude: 51.5007,
    longitude: -0.1246,
    address: 'Westminster, London SW1A 0AA',
    rating: 4.8,
  ),
  Place(
    id: 'ld-002',
    name: 'Tower Bridge',
    description: 'Ponte basculante famosa, uma das mais reconhecidas do mundo.',
    category: PlaceCategory.tourist,
    latitude: 51.5055,
    longitude: -0.0754,
    address: 'Tower Bridge Rd, London SE1 2UP',
    rating: 4.7,
  ),
  Place(
    id: 'ld-003',
    name: 'British Museum',
    description:
        'Museu com vasta coleção de arte e antiguidades do mundo todo.',
    category: PlaceCategory.museum,
    latitude: 51.5194,
    longitude: -0.1270,
    address: 'Great Russell St, London WC1B 3DG',
    rating: 4.8,
  ),
  Place(
    id: 'ld-004',
    name: 'Buckingham Palace',
    description: 'Residência oficial da monarquia britânica desde 1837.',
    category: PlaceCategory.tourist,
    latitude: 51.5014,
    longitude: -0.1419,
    address: 'London SW1A 1AA',
    rating: 4.6,
  ),
  Place(
    id: 'ld-005',
    name: 'Hyde Park',
    description: 'Um dos maiores parques de Londres, perfeito para passeios.',
    category: PlaceCategory.park,
    latitude: 51.5073,
    longitude: -0.1657,
    address: 'London W2 2UH',
    rating: 4.7,
  ),
  Place(
    id: 'ld-006',
    name: 'The Shard',
    description: 'Arranha-céu com vista panorâmica de 360° de Londres.',
    category: PlaceCategory.tourist,
    latitude: 51.5045,
    longitude: -0.0865,
    address: '32 London Bridge St, London SE1 9SG',
    rating: 4.5,
  ),
  Place(
    id: 'ld-007',
    name: 'Dishoom Covent Garden',
    description: 'Restaurante indiano inspirado nos cafés de Bombaim.',
    category: PlaceCategory.restaurant,
    latitude: 51.5130,
    longitude: -0.1215,
    address: '12 Upper St Martin\'s Lane, London WC2H 9FB',
    rating: 4.6,
  ),
  Place(
    id: 'ld-008',
    name: 'Borough Market',
    description: 'Mercado histórico com comida gourmet e produtos artesanais.',
    category: PlaceCategory.restaurant,
    latitude: 51.5055,
    longitude: -0.0909,
    address: '8 Southwark St, London SE1 1TL',
    rating: 4.5,
  ),
  Place(
    id: 'ld-009',
    name: 'The Churchill Arms',
    description: 'Pub histórico decorado com flores, serve comida tailandesa.',
    category: PlaceCategory.bar,
    latitude: 51.5065,
    longitude: -0.1942,
    address: '119 Kensington Church St, London W8 7LN',
    rating: 4.4,
  ),
  Place(
    id: 'ld-010',
    name: 'Westminster Abbey',
    description: 'Igreja gótica onde são coroados os monarcas britânicos.',
    category: PlaceCategory.church,
    latitude: 51.4993,
    longitude: -0.1273,
    address: '20 Deans Yd, Westminster, London SW1P 3PA',
    rating: 4.7,
  ),
  Place(
    id: 'ld-011',
    name: "St Paul's Cathedral",
    description:
        'Catedral anglicana com cúpula icônica projetada por Christopher Wren.',
    category: PlaceCategory.church,
    latitude: 51.5138,
    longitude: -0.0984,
    address: "St. Paul's Churchyard, London EC4M 8AD",
    rating: 4.7,
  ),
  Place(
    id: 'ld-012',
    name: 'Sketch',
    description: 'Restaurante e bar excêntrico com interiores artísticos.',
    category: PlaceCategory.restaurant,
    latitude: 51.5142,
    longitude: -0.1410,
    address: '9 Conduit St, London W1S 2XG',
    rating: 4.3,
  ),
];

// ─── PARIS ──────────────────────────────────────────────────────────────────────
const List<Place> _parisPlaces = [
  Place(
    id: 'pr-001',
    name: 'Torre Eiffel',
    description: 'Monumento mais visitado do mundo, símbolo de Paris.',
    category: PlaceCategory.tourist,
    latitude: 48.8584,
    longitude: 2.2945,
    address: 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris',
    rating: 4.7,
  ),
  Place(
    id: 'pr-002',
    name: 'Musée du Louvre',
    description: 'Maior museu de arte do mundo, com a Mona Lisa.',
    category: PlaceCategory.museum,
    latitude: 48.8606,
    longitude: 2.3376,
    address: 'Rue de Rivoli, 75001 Paris',
    rating: 4.8,
  ),
  Place(
    id: 'pr-003',
    name: 'Cathédrale Notre-Dame',
    description: 'Catedral gótica medieval no coração de Paris.',
    category: PlaceCategory.church,
    latitude: 48.8530,
    longitude: 2.3499,
    address: '6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris',
    rating: 4.7,
  ),
  Place(
    id: 'pr-004',
    name: 'Arc de Triomphe',
    description: 'Monumento histórico no topo dos Champs-Élysées.',
    category: PlaceCategory.tourist,
    latitude: 48.8738,
    longitude: 2.2950,
    address: "Place Charles de Gaulle, 75008 Paris",
    rating: 4.7,
  ),
  Place(
    id: 'pr-005',
    name: 'Jardin du Luxembourg',
    description: 'Jardim público com esculturas, fontes e área para crianças.',
    category: PlaceCategory.park,
    latitude: 48.8462,
    longitude: 2.3372,
    address: '75006 Paris',
    rating: 4.7,
  ),
  Place(
    id: 'pr-006',
    name: 'Le Comptoir du Relais',
    description: 'Bistrô parisiense clássico com cozinha francesa refinada.',
    category: PlaceCategory.restaurant,
    latitude: 48.8516,
    longitude: 2.3384,
    address: '9 Carrefour de l\'Odéon, 75006 Paris',
    rating: 4.4,
  ),
  Place(
    id: 'pr-007',
    name: 'Café de Flore',
    description: 'Café histórico frequentado por escritores e artistas.',
    category: PlaceCategory.bar,
    latitude: 48.8542,
    longitude: 2.3326,
    address: '172 Boulevard Saint-Germain, 75006 Paris',
    rating: 4.3,
  ),
  Place(
    id: 'pr-008',
    name: 'Sacré-Cœur',
    description: 'Basílica no topo de Montmartre com vista panorâmica.',
    category: PlaceCategory.church,
    latitude: 48.8867,
    longitude: 2.3431,
    address: '35 Rue du Chevalier de la Barre, 75018 Paris',
    rating: 4.7,
  ),
  Place(
    id: 'pr-009',
    name: 'Musée d\'Orsay',
    description: 'Museu de arte impressionista em antiga estação de trem.',
    category: PlaceCategory.museum,
    latitude: 48.8600,
    longitude: 2.3266,
    address: '1 Rue de la Légion d\'Honneur, 75007 Paris',
    rating: 4.8,
  ),
  Place(
    id: 'pr-010',
    name: 'Le Jules Verne',
    description: 'Restaurante estrelado Michelin na Torre Eiffel.',
    category: PlaceCategory.restaurant,
    latitude: 48.8583,
    longitude: 2.2945,
    address: 'Avenue Gustave Eiffel, 75007 Paris',
    rating: 4.5,
  ),
];

// ─── BARCELONA ──────────────────────────────────────────────────────────────────
const List<Place> _barcelonaPlaces = [
  Place(
    id: 'bc-001',
    name: 'Sagrada Família',
    description: 'Basílica de Gaudí, obra-prima do modernismo catalão.',
    category: PlaceCategory.church,
    latitude: 41.4036,
    longitude: 2.1744,
    address: 'Carrer de Mallorca, 401, 08013 Barcelona',
    rating: 4.8,
  ),
  Place(
    id: 'bc-002',
    name: 'Park Güell',
    description:
        'Parque público com jardins e elementos arquitetônicos de Gaudí.',
    category: PlaceCategory.park,
    latitude: 41.4145,
    longitude: 2.1527,
    address: '08024 Barcelona',
    rating: 4.6,
  ),
  Place(
    id: 'bc-003',
    name: 'La Rambla',
    description: 'Famosa avenida pedestre com artistas de rua e lojas.',
    category: PlaceCategory.tourist,
    latitude: 41.3811,
    longitude: 2.1744,
    address: 'La Rambla, 08002 Barcelona',
    rating: 4.4,
  ),
  Place(
    id: 'bc-004',
    name: 'Casa Batlló',
    description: 'Edifício modernista de Gaudí com fachada ondulante.',
    category: PlaceCategory.museum,
    latitude: 41.3916,
    longitude: 2.1649,
    address: 'Passeig de Gràcia, 43, 08007 Barcelona',
    rating: 4.7,
  ),
  Place(
    id: 'bc-005',
    name: 'Mercat de la Boqueria',
    description: 'Mercado público vibrante com comida fresca e tapas.',
    category: PlaceCategory.restaurant,
    latitude: 41.3816,
    longitude: 2.1714,
    address: 'La Rambla, 91, 08001 Barcelona',
    rating: 4.5,
  ),
  Place(
    id: 'bc-006',
    name: 'Cervecería Catalana',
    description: 'Bar de tapas popular com ampla variedade de petiscos.',
    category: PlaceCategory.bar,
    latitude: 41.3939,
    longitude: 2.1601,
    address: 'Carrer de Mallorca, 236, 08008 Barcelona',
    rating: 4.4,
  ),
  Place(
    id: 'bc-007',
    name: 'Barceloneta Beach',
    description: 'Praia urbana popular próxima ao centro da cidade.',
    category: PlaceCategory.beach,
    latitude: 41.3770,
    longitude: 2.1896,
    address: 'Passeig Marítim de la Barceloneta, 08003 Barcelona',
    rating: 4.3,
  ),
  Place(
    id: 'bc-008',
    name: 'Camp Nou',
    description: 'Estádio do FC Barcelona, o maior da Europa.',
    category: PlaceCategory.tourist,
    latitude: 41.3809,
    longitude: 2.1228,
    address: 'C. d\'Arístides Maillol, 12, 08028 Barcelona',
    rating: 4.7,
  ),
];

// ─── AMSTERDAM ──────────────────────────────────────────────────────────────────
const List<Place> _amsterdamPlaces = [
  Place(
    id: 'am-001',
    name: 'Rijksmuseum',
    description: 'Museu nacional com obras de Rembrandt e Vermeer.',
    category: PlaceCategory.museum,
    latitude: 52.3600,
    longitude: 4.8852,
    address: 'Museumstraat 1, 1071 XX Amsterdam',
    rating: 4.8,
  ),
  Place(
    id: 'am-002',
    name: 'Van Gogh Museum',
    description: 'Maior coleção de obras de Vincent van Gogh.',
    category: PlaceCategory.museum,
    latitude: 52.3584,
    longitude: 4.8811,
    address: 'Museumplein 6, 1071 DJ Amsterdam',
    rating: 4.7,
  ),
  Place(
    id: 'am-003',
    name: 'Anne Frank House',
    description: 'Casa-museu onde Anne Frank escreveu seu diário.',
    category: PlaceCategory.museum,
    latitude: 52.3752,
    longitude: 4.8840,
    address: 'Westermarkt 20, 1016 GV Amsterdam',
    rating: 4.6,
  ),
  Place(
    id: 'am-004',
    name: 'Vondelpark',
    description: 'Maior parque público da cidade, ideal para ciclismo.',
    category: PlaceCategory.park,
    latitude: 52.3579,
    longitude: 4.8686,
    address: '1071 AA Amsterdam',
    rating: 4.6,
  ),
  Place(
    id: 'am-005',
    name: 'De Kas',
    description: 'Restaurante em estufa com ingredientes do próprio jardim.',
    category: PlaceCategory.restaurant,
    latitude: 52.3532,
    longitude: 4.9385,
    address: 'Kamerlingh Onneslaan 3, 1097 DE Amsterdam',
    rating: 4.5,
  ),
  Place(
    id: 'am-006',
    name: 'Café de Jaren',
    description: 'Café espaçoso com terraço no canal.',
    category: PlaceCategory.bar,
    latitude: 52.3693,
    longitude: 4.8969,
    address: 'Nieuwe Doelenstraat 20, 1012 CP Amsterdam',
    rating: 4.3,
  ),
  Place(
    id: 'am-007',
    name: 'Dam Square',
    description: 'Praça central histórica com o Palácio Real.',
    category: PlaceCategory.tourist,
    latitude: 52.3730,
    longitude: 4.8936,
    address: 'Dam, 1012 JS Amsterdam',
    rating: 4.4,
  ),
];

// ─── ROMA ───────────────────────────────────────────────────────────────────────
const List<Place> _romePlaces = [
  Place(
    id: 'rm-001',
    name: 'Coliseu',
    description: 'Anfiteatro romano antigo, símbolo de Roma.',
    category: PlaceCategory.tourist,
    latitude: 41.8902,
    longitude: 12.4922,
    address: 'Piazza del Colosseo, 1, 00184 Roma',
    rating: 4.8,
  ),
  Place(
    id: 'rm-002',
    name: 'Fontana di Trevi',
    description: 'Fonte barroca monumental, tradição de jogar moedas.',
    category: PlaceCategory.tourist,
    latitude: 41.9009,
    longitude: 12.4833,
    address: 'Piazza di Trevi, 00187 Roma',
    rating: 4.7,
  ),
  Place(
    id: 'rm-003',
    name: 'Vaticano - Basílica de São Pedro',
    description: 'Maior igreja do mundo, centro da cristandade católica.',
    category: PlaceCategory.church,
    latitude: 41.9022,
    longitude: 12.4539,
    address: 'Piazza San Pietro, 00120 Città del Vaticano',
    rating: 4.8,
  ),
  Place(
    id: 'rm-004',
    name: 'Museus Vaticanos',
    description: 'Complexo de museus com Capela Sistina de Michelangelo.',
    category: PlaceCategory.museum,
    latitude: 41.9065,
    longitude: 12.4536,
    address: 'Viale Vaticano, 00165 Roma',
    rating: 4.7,
  ),
  Place(
    id: 'rm-005',
    name: 'Pantheon',
    description: 'Templo romano com cúpula impressionante de 2000 anos.',
    category: PlaceCategory.tourist,
    latitude: 41.8986,
    longitude: 12.4769,
    address: 'Piazza della Rotonda, 00186 Roma',
    rating: 4.7,
  ),
  Place(
    id: 'rm-006',
    name: 'Villa Borghese',
    description: 'Parque amplo com museus, jardins e lago.',
    category: PlaceCategory.park,
    latitude: 41.9142,
    longitude: 12.4923,
    address: 'Piazzale Napoleone I, 00197 Roma',
    rating: 4.6,
  ),
  Place(
    id: 'rm-007',
    name: 'Trattoria Da Enzo',
    description: 'Trattoria tradicional romana em Trastevere.',
    category: PlaceCategory.restaurant,
    latitude: 41.8897,
    longitude: 12.4697,
    address: 'Via dei Vascellari, 29, 00153 Roma',
    rating: 4.5,
  ),
  Place(
    id: 'rm-008',
    name: 'Piazza Navona',
    description: 'Praça barroca com três fontes e cafés ao ar livre.',
    category: PlaceCategory.tourist,
    latitude: 41.8992,
    longitude: 12.4731,
    address: 'Piazza Navona, 00186 Roma',
    rating: 4.6,
  ),
];

// ─── BERLIN ─────────────────────────────────────────────────────────────────────
const List<Place> _berlinPlaces = [
  Place(
    id: 'be-001',
    name: 'Portão de Brandemburgo',
    description: 'Monumento icônico e símbolo da reunificação alemã.',
    category: PlaceCategory.tourist,
    latitude: 52.5163,
    longitude: 13.3777,
    address: 'Pariser Platz, 10117 Berlin',
    rating: 4.7,
  ),
  Place(
    id: 'be-002',
    name: 'Muro de Berlim - East Side Gallery',
    description: 'Galeria ao ar livre no trecho preservado do Muro de Berlim.',
    category: PlaceCategory.tourist,
    latitude: 52.5053,
    longitude: 13.4397,
    address: 'Mühlenstraße, 10243 Berlin',
    rating: 4.5,
  ),
  Place(
    id: 'be-003',
    name: 'Ilha dos Museus',
    description: 'Complexo de cinco museus de classe mundial.',
    category: PlaceCategory.museum,
    latitude: 52.5194,
    longitude: 13.3978,
    address: 'Bodestraße, 10178 Berlin',
    rating: 4.7,
  ),
  Place(
    id: 'be-004',
    name: 'Reichstag',
    description: 'Edifício do parlamento alemão com cúpula de vidro.',
    category: PlaceCategory.tourist,
    latitude: 52.5186,
    longitude: 13.3762,
    address: 'Platz der Republik 1, 11011 Berlin',
    rating: 4.6,
  ),
  Place(
    id: 'be-005',
    name: 'Tiergarten',
    description: 'Enorme parque urbano no centro de Berlim.',
    category: PlaceCategory.park,
    latitude: 52.5144,
    longitude: 13.3501,
    address: 'Straße des 17. Juni, 10785 Berlin',
    rating: 4.6,
  ),
  Place(
    id: 'be-006',
    name: 'Curry 36',
    description: 'Lanchonete icônica de currywurst berlinense.',
    category: PlaceCategory.restaurant,
    latitude: 52.4994,
    longitude: 13.3881,
    address: 'Mehringdamm 36, 10961 Berlin',
    rating: 4.3,
  ),
  Place(
    id: 'be-007',
    name: 'Clärchens Ballhaus',
    description: 'Salão de dança histórico com restaurante e bar.',
    category: PlaceCategory.bar,
    latitude: 52.5275,
    longitude: 13.3973,
    address: 'Auguststraße 24, 10117 Berlin',
    rating: 4.4,
  ),
];

// ─── ATHENS ─────────────────────────────────────────────────────────────────────
const List<Place> _athensPlaces = [
  Place(
    id: 'at-001',
    name: 'Acrópole',
    description: 'Antiga cidadela com o Partenon, símbolo da Grécia Antiga.',
    category: PlaceCategory.tourist,
    latitude: 37.9715,
    longitude: 23.7257,
    address: 'Athens 105 58, Greece',
    rating: 4.8,
  ),
  Place(
    id: 'at-002',
    name: 'Partenon',
    description:
        'Templo dedicado à deusa Atena, obra-prima da arquitetura clássica.',
    category: PlaceCategory.tourist,
    latitude: 37.9715,
    longitude: 23.7266,
    address: 'Acropolis, Athens 105 58',
    rating: 4.8,
  ),
  Place(
    id: 'at-003',
    name: 'Museu da Acrópole',
    description: 'Museu moderno com artefatos da Grécia Antiga.',
    category: PlaceCategory.museum,
    latitude: 37.9684,
    longitude: 23.7283,
    address: 'Dionysiou Areopagitou 15, Athens 117 42',
    rating: 4.7,
  ),
  Place(
    id: 'at-004',
    name: 'Plaka',
    description: 'Bairro histórico com vielas pitorescas e tavernas.',
    category: PlaceCategory.tourist,
    latitude: 37.9733,
    longitude: 23.7279,
    address: 'Plaka, Athens 105 58',
    rating: 4.6,
  ),
  Place(
    id: 'at-005',
    name: 'Jardim Nacional',
    description: 'Oásis verde no centro de Atenas com lagos e pavões.',
    category: PlaceCategory.park,
    latitude: 37.9742,
    longitude: 23.7377,
    address: 'Leof. Vasilisis Amalias 1, Athens 105 57',
    rating: 4.5,
  ),
  Place(
    id: 'at-006',
    name: 'Taverna Klimataria',
    description: 'Taverna tradicional grega com música ao vivo.',
    category: PlaceCategory.restaurant,
    latitude: 37.9796,
    longitude: 23.7227,
    address: 'Klepsidras 5, Athens 105 55',
    rating: 4.4,
  ),
  Place(
    id: 'at-007',
    name: 'A for Athens Bar',
    description: 'Bar de coquetel no terraço com vista para Acrópole.',
    category: PlaceCategory.bar,
    latitude: 37.9753,
    longitude: 23.7268,
    address: 'Miaouli 2-4, Athens 105 54',
    rating: 4.3,
  ),
];

// ─── BUDAPEST ───────────────────────────────────────────────────────────────────
const List<Place> _budapestPlaces = [
  Place(
    id: 'bu-001',
    name: 'Parlamento Húngaro',
    description: 'Edifício gótico do parlamento às margens do Danúbio.',
    category: PlaceCategory.tourist,
    latitude: 47.5070,
    longitude: 19.0456,
    address: 'Kossuth Lajos tér 1-3, 1055 Budapest',
    rating: 4.8,
  ),
  Place(
    id: 'bu-002',
    name: 'Castelo de Buda',
    description: 'Palácio histórico no topo da colina com vista panorâmica.',
    category: PlaceCategory.tourist,
    latitude: 47.4963,
    longitude: 19.0395,
    address: 'Szent György tér 2, 1014 Budapest',
    rating: 4.7,
  ),
  Place(
    id: 'bu-003',
    name: 'Termas Széchenyi',
    description: 'Maior complexo de banhos termais da Europa.',
    category: PlaceCategory.tourist,
    latitude: 47.5196,
    longitude: 19.0817,
    address: 'Állatkerti krt. 9-11, 1146 Budapest',
    rating: 4.6,
  ),
  Place(
    id: 'bu-004',
    name: 'Basílica de Santo Estêvão',
    description: 'Maior igreja de Budapeste com cúpula imponente.',
    category: PlaceCategory.church,
    latitude: 47.5009,
    longitude: 19.0534,
    address: 'Szent István tér 1, 1051 Budapest',
    rating: 4.7,
  ),
  Place(
    id: 'bu-005',
    name: 'Parque da Cidade',
    description: 'Parque público com castelo, lago e zona de lazer.',
    category: PlaceCategory.park,
    latitude: 47.5145,
    longitude: 19.0829,
    address: 'Budapest, 1146',
    rating: 4.6,
  ),
  Place(
    id: 'bu-006',
    name: 'Café Gerbeaud',
    description: 'Café histórico desde 1858, famoso por doces húngaros.',
    category: PlaceCategory.restaurant,
    latitude: 47.4959,
    longitude: 19.0513,
    address: 'Vörösmarty tér 7, 1051 Budapest',
    rating: 4.5,
  ),
  Place(
    id: 'bu-007',
    name: 'Szimpla Kert',
    description: 'Ruin bar mais famoso de Budapeste, com ambiente alternativo.',
    category: PlaceCategory.bar,
    latitude: 47.4968,
    longitude: 19.0624,
    address: 'Kazinczy u. 14, 1075 Budapest',
    rating: 4.4,
  ),
];

// ─── LISBON ─────────────────────────────────────────────────────────────────────
const List<Place> _lisbonPlaces = [
  Place(
    id: 'li-001',
    name: 'Torre de Belém',
    description:
        'Torre fortificada do século XVI, patrimônio mundial da UNESCO.',
    category: PlaceCategory.tourist,
    latitude: 38.6916,
    longitude: -9.2160,
    address: 'Av. Brasília, 1400-038 Lisboa',
    rating: 4.6,
  ),
  Place(
    id: 'li-002',
    name: 'Mosteiro dos Jerónimos',
    description: 'Mosteiro manuelino com arquitetura deslumbrante.',
    category: PlaceCategory.church,
    latitude: 38.6978,
    longitude: -9.2064,
    address: 'Praça do Império 1400-206 Lisboa',
    rating: 4.7,
  ),
  Place(
    id: 'li-003',
    name: 'Castelo de São Jorge',
    description: 'Castelo medieval no topo da colina com vista de Lisboa.',
    category: PlaceCategory.tourist,
    latitude: 38.7139,
    longitude: -9.1334,
    address: 'R. de Santa Cruz do Castelo, 1100-129 Lisboa',
    rating: 4.5,
  ),
  Place(
    id: 'li-004',
    name: 'Oceanário de Lisboa',
    description:
        'Um dos maiores aquários da Europa com diversas espécies marinhas.',
    category: PlaceCategory.museum,
    latitude: 38.7633,
    longitude: -9.0935,
    address: 'Esplanada Dom Carlos I s/nº, 1990-005 Lisboa',
    rating: 4.7,
  ),
  Place(
    id: 'li-005',
    name: 'Parque Eduardo VII',
    description: 'Parque formal com vista panorâmica de Lisboa.',
    category: PlaceCategory.park,
    latitude: 38.7297,
    longitude: -9.1521,
    address: '1070-051 Lisboa',
    rating: 4.4,
  ),
  Place(
    id: 'li-006',
    name: 'Time Out Market',
    description: 'Mercado gastronômico com os melhores chefs de Lisboa.',
    category: PlaceCategory.restaurant,
    latitude: 38.7066,
    longitude: -9.1452,
    address: 'Av. 24 de Julho 49, 1200-479 Lisboa',
    rating: 4.5,
  ),
  Place(
    id: 'li-007',
    name: 'Pastéis de Belém',
    description:
        'Confeitaria famosa pelos pastéis de nata originais desde 1837.',
    category: PlaceCategory.restaurant,
    latitude: 38.6976,
    longitude: -9.2031,
    address: 'R. de Belém 84-92, 1300-085 Lisboa',
    rating: 4.6,
  ),
  Place(
    id: 'li-008',
    name: 'Park Bar',
    description: 'Bar no terraço com vista panorâmica da cidade.',
    category: PlaceCategory.bar,
    latitude: 38.7163,
    longitude: -9.1451,
    address: 'Calçada do Combro 58, 1200-114 Lisboa',
    rating: 4.3,
  ),
];

// ─── VIENNA ─────────────────────────────────────────────────────────────────────
const List<Place> _viennaPlaces = [
  Place(
    id: 'vi-001',
    name: 'Palácio de Schönbrunn',
    description: 'Palácio barroco imperial com jardins magníficos.',
    category: PlaceCategory.tourist,
    latitude: 48.1844,
    longitude: 16.3122,
    address: 'Schönbrunner Schloßstraße 47, 1130 Wien',
    rating: 4.7,
  ),
  Place(
    id: 'vi-002',
    name: 'Catedral de Santo Estêvão',
    description: 'Catedral gótica icônica no centro de Viena.',
    category: PlaceCategory.church,
    latitude: 48.2085,
    longitude: 16.3730,
    address: 'Stephansplatz 3, 1010 Wien',
    rating: 4.7,
  ),
  Place(
    id: 'vi-003',
    name: 'Palácio Belvedere',
    description: 'Complexo de palácios barrocos com museu de arte.',
    category: PlaceCategory.museum,
    latitude: 48.1915,
    longitude: 16.3807,
    address: 'Prinz Eugen-Straße 27, 1030 Wien',
    rating: 4.7,
  ),
  Place(
    id: 'vi-004',
    name: 'Ópera Estatal de Viena',
    description: 'Uma das casas de ópera mais importantes do mundo.',
    category: PlaceCategory.tourist,
    latitude: 48.2029,
    longitude: 16.3689,
    address: 'Opernring 2, 1010 Wien',
    rating: 4.6,
  ),
  Place(
    id: 'vi-005',
    name: 'Prater',
    description: 'Parque de diversões histórico com a famosa Roda Gigante.',
    category: PlaceCategory.park,
    latitude: 48.2166,
    longitude: 16.3958,
    address: 'Prater, 1020 Wien',
    rating: 4.5,
  ),
  Place(
    id: 'vi-006',
    name: 'Café Central',
    description: 'Café histórico frequentado por intelectuais e artistas.',
    category: PlaceCategory.restaurant,
    latitude: 48.2105,
    longitude: 16.3658,
    address: 'Herrengasse 14, 1010 Wien',
    rating: 4.4,
  ),
  Place(
    id: 'vi-007',
    name: 'Figlmüller',
    description: 'Restaurante famoso pelo schnitzel gigante vienense.',
    category: PlaceCategory.restaurant,
    latitude: 48.2094,
    longitude: 16.3743,
    address: 'Wollzeile 5, 1010 Wien',
    rating: 4.5,
  ),
  Place(
    id: 'vi-008',
    name: 'Loos American Bar',
    description: 'Bar icônico projetado por Adolf Loos em 1908.',
    category: PlaceCategory.bar,
    latitude: 48.2087,
    longitude: 16.3701,
    address: 'Kärntner Durchgang 10, 1010 Wien',
    rating: 4.3,
  ),
];

const List<Place> _saoPauloPlaces = [
  Place(
    id: 'sp-001',
    name: 'Mercadão Municipal',
    description: 'Mercado histórico com gastronomia típica e frutas exóticas.',
    category: PlaceCategory.restaurant,
    latitude: -23.5415,
    longitude: -46.6289,
    address: 'R. da Cantareira, 306 - Centro',
    rating: 4.7,
  ),
  Place(
    id: 'sp-002',
    name: 'Pinacoteca do Estado',
    description: 'Museu de arte com um dos mais importantes acervos do Brasil.',
    category: PlaceCategory.museum,
    latitude: -23.5346,
    longitude: -46.6321,
    address: 'Praça da Luz, 2 - Luz',
    rating: 4.8,
  ),
  Place(
    id: 'sp-003',
    name: 'Parque Ibirapuera',
    description: 'Principal parque urbano de São Paulo, ideal para caminhadas.',
    category: PlaceCategory.park,
    latitude: -23.5874,
    longitude: -46.6576,
    address: 'Av. Pedro Álvares Cabral - Vila Mariana',
    rating: 4.8,
  ),
  Place(
    id: 'sp-004',
    name: 'Bar do Espeto',
    description: 'Clássico boteco paulistano com petiscos tradicionais.',
    category: PlaceCategory.bar,
    latitude: -23.5600,
    longitude: -46.6610,
    address: 'R. Augusta, 2325 - Jardins',
    rating: 4.2,
  ),
  Place(
    id: 'sp-005',
    name: 'Catedral da Sé',
    description: 'Icônica catedral neogótica no coração de São Paulo.',
    category: PlaceCategory.church,
    latitude: -23.5503,
    longitude: -46.6339,
    address: 'Praça da Sé, s/n - Sé',
    rating: 4.6,
  ),
  Place(
    id: 'sp-006',
    name: 'Feira da Liberdade',
    description:
        'Maior feira oriental fora do Japão, com gastronomia e cultura.',
    category: PlaceCategory.shopping,
    latitude: -23.5588,
    longitude: -46.6328,
    address: 'Praça da Liberdade - Liberdade',
    rating: 4.5,
  ),
];

const List<Place> _recifePlaces = [
  Place(
    id: 're-001',
    name: 'Marco Zero',
    description:
        'Ponto histórico no centro do Recife Antigo com shows e feiras.',
    category: PlaceCategory.tourist,
    latitude: -8.0630,
    longitude: -34.8711,
    address: 'Praça Rio Branco - Recife Antigo',
    rating: 4.7,
  ),
  Place(
    id: 're-002',
    name: 'Praia de Boa Viagem',
    description:
        'Uma das praias mais famosas do Nordeste, com piscinas naturais.',
    category: PlaceCategory.beach,
    latitude: -8.1197,
    longitude: -34.8995,
    address: 'Av. Boa Viagem - Boa Viagem',
    rating: 4.5,
  ),
  Place(
    id: 're-003',
    name: 'Instituto Ricardo Brennand',
    description: 'Complexo cultural com castelo medieval, museu e jardins.',
    category: PlaceCategory.museum,
    latitude: -8.0539,
    longitude: -34.9523,
    address: 'Alameda Antônio Brennand - Várzea',
    rating: 4.9,
  ),
  Place(
    id: 're-004',
    name: 'Restaurante Leite',
    description: 'Restaurante mais antigo do Brasil em funcionamento contínuo.',
    category: PlaceCategory.restaurant,
    latitude: -8.0597,
    longitude: -34.8801,
    address: 'Praça Joaquim Nabuco, 147 - Santo Antônio',
    rating: 4.4,
  ),
  Place(
    id: 're-005',
    name: 'Parque 13 de Maio',
    description:
        'Parque histórico no centro da cidade, perfeito para descanso.',
    category: PlaceCategory.park,
    latitude: -8.0574,
    longitude: -34.8838,
    address: 'R. do Hospício - Boa Vista',
    rating: 4.1,
  ),
  Place(
    id: 're-006',
    name: 'Spazio Libero',
    description: 'Bar e restaurante com vista para o rio e música ao vivo.',
    category: PlaceCategory.bar,
    latitude: -8.0645,
    longitude: -34.8718,
    address: 'Av. Marquês de Olinda - Bairro do Recife',
    rating: 4.3,
  ),
];

const List<Place> _rioDePlacas = [
  Place(
    id: 'rj-001',
    name: 'Cristo Redentor',
    description:
        'Uma das sete maravilhas do mundo moderno, no topo do Corcovado.',
    category: PlaceCategory.tourist,
    latitude: -22.9519,
    longitude: -43.2105,
    address: 'Parque Nacional da Tijuca - Alto da Boa Vista',
    rating: 4.9,
  ),
  Place(
    id: 'rj-002',
    name: 'Praia de Copacabana',
    description: 'A praia mais famosa do mundo, repleta de cultura carioca.',
    category: PlaceCategory.beach,
    latitude: -22.9711,
    longitude: -43.1823,
    address: 'Av. Atlântica - Copacabana',
    rating: 4.7,
  ),
  Place(
    id: 'rj-003',
    name: 'Museu Nacional de Belas Artes',
    description: 'Principal museu de artes visuais do Brasil.',
    category: PlaceCategory.museum,
    latitude: -22.9099,
    longitude: -43.1759,
    address: 'Av. Rio Branco, 199 - Centro',
    rating: 4.6,
  ),
  Place(
    id: 'rj-004',
    name: 'Restaurante Aprazível',
    description:
        'Gastronomia brasileira contemporânea com vista para Santa Teresa.',
    category: PlaceCategory.restaurant,
    latitude: -22.9200,
    longitude: -43.1831,
    address: 'R. Aprazível, 62 - Santa Teresa',
    rating: 4.8,
  ),
  Place(
    id: 'rj-005',
    name: 'Jardim Botânico',
    description: 'Espaço verde de 137 hectares com mais de 6500 espécies.',
    category: PlaceCategory.park,
    latitude: -22.9667,
    longitude: -43.2250,
    address: 'R. Jardim Botânico, 1008 - Jardim Botânico',
    rating: 4.7,
  ),
  Place(
    id: 'rj-006',
    name: 'Bar do Mineiro',
    description: 'Boteco carioca histórico com feijoada e chope gelado.',
    category: PlaceCategory.bar,
    latitude: -22.9208,
    longitude: -43.1812,
    address: 'R. Paschoal Carlos Magno, 99 - Santa Teresa',
    rating: 4.5,
  ),
];

const List<Place> _genericPlaces = [
  Place(
    id: 'gen-001',
    name: 'Praça Central',
    description: 'Praça central do bairro, ponto de encontro da comunidade.',
    category: PlaceCategory.tourist,
    latitude: 0,
    longitude: 0,
    rating: 4.0,
  ),
  Place(
    id: 'gen-002',
    name: 'Mercado Municipal',
    description: 'Mercado local com produtos frescos e comida regional.',
    category: PlaceCategory.restaurant,
    latitude: 0,
    longitude: 0,
    rating: 4.1,
  ),
  Place(
    id: 'gen-003',
    name: 'Parque Municipal',
    description: 'Parque para atividades ao ar livre e lazer em família.',
    category: PlaceCategory.park,
    latitude: 0,
    longitude: 0,
    rating: 4.2,
  ),
  Place(
    id: 'gen-004',
    name: 'Igreja Matriz',
    description: 'Igreja histórica tombada pelo patrimônio municipal.',
    category: PlaceCategory.church,
    latitude: 0,
    longitude: 0,
    rating: 4.3,
  ),
  Place(
    id: 'gen-005',
    name: 'Museu Regional',
    description: 'Museu com acervo da história e cultura local.',
    category: PlaceCategory.museum,
    latitude: 0,
    longitude: 0,
    rating: 4.0,
  ),
  Place(
    id: 'gen-006',
    name: 'Bar & Restaurante do Centro',
    description: 'O ponto gastronômico mais popular do bairro.',
    category: PlaceCategory.bar,
    latitude: 0,
    longitude: 0,
    rating: 4.4,
  ),
];

/// Retorna uma lista de lugares mock baseada na cidade selecionada.
/// Em produção isso poderia ser substituído por uma chamada à API do Overpass/Google Places.
List<Place> getMockPlacesForCity(String cityName) {
  final lower = cityName.toLowerCase();

  // Cidades europeias
  if (lower.contains('london') || lower.contains('londres')) {
    return _londonPlaces;
  }
  if (lower.contains('paris')) {
    return _parisPlaces;
  }
  if (lower.contains('barcelona')) {
    return _barcelonaPlaces;
  }
  if (lower.contains('amsterdam') || lower.contains('amsterdã')) {
    return _amsterdamPlaces;
  }
  if (lower.contains('roma') || lower.contains('rome')) {
    return _romePlaces;
  }
  if (lower.contains('berlin')) {
    return _berlinPlaces;
  }
  if (lower.contains('athens') || lower.contains('atenas')) {
    return _athensPlaces;
  }
  if (lower.contains('budapest')) {
    return _budapestPlaces;
  }
  if (lower.contains('lisbon') || lower.contains('lisboa')) {
    return _lisbonPlaces;
  }
  if (lower.contains('vienna') || lower.contains('viena')) {
    return _viennaPlaces;
  }

  // Cidades brasileiras (fallback para compatibilidade)
  if (lower.contains('são paulo') ||
      lower.contains('sao paulo') ||
      lower.contains('sp')) {
    return _saoPauloPlaces;
  }
  if (lower.contains('recife') || lower.contains('pernambuco')) {
    return _recifePlaces;
  }
  if (lower.contains('rio') || lower.contains('rj')) {
    return _rioDePlacas;
  }

  // Para qualquer outra cidade, retorna lugares genéricos
  return _genericPlaces;
}
