// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HBdRz-A9Km0g8-lGxtBFfmysshy51uE',
    appId: '1:1029953179970:web:8ffcb16a5c27c185aff8db',
    messagingSenderId: '1029953179970',
    projectId: 'coral-quest',
    authDomain: 'coral-quest.firebaseapp.com',
    storageBucket: 'coral-quest.firebasestorage.app',
    measurementId: 'G-H1DNWGY2MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8YEuxg7jrW93ALgEowEtxz4r-HwLQG7Y',
    appId: '1:1029953179970:android:b4b4f78741f5c412aff8db',
    messagingSenderId: '1029953179970',
    projectId: 'coral-quest',
    storageBucket: 'coral-quest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWod0ENKsr37lwtEJDSuWpuj3wbWnJKM',
    appId: '1:1029953179970:ios:eaa8f78b70d6e5a4aff8db',
    messagingSenderId: '1029953179970',
    projectId: 'coral-quest',
    storageBucket: 'coral-quest.firebasestorage.app',
    iosBundleId: 'com.bairromatch.vibeCoralQuest',
  );

}